### ISSUE TITLE
Split TF tree in Iris maze

### ISSUE THREAD

**Issue by Ryanf55** [ArduPilot/ardupilot_gz#41]
## Expected

Can launch iris maze and have a single TF tree with no error in RVIZ

## Actual

Rviz complains about missing frames, and the TF tree is split. On two computers, it only happens on one of them. Unclear what the difference is. I'll chase it down.

## Steps to reproduce

* Create a fresh ROS 2 workspace
* Install the ros_gz dependencies per the README with VCS
* Build all packages up to ros_gz_bringup
* Launch iris maze
* Run TF viewer: `ros2 run tf2_tools view_frames `

## Logs

See the attached PDF for the desired  frame tree

[frames_2023-11-11_21.50.14.pdf](https://github.com/ArduPilot/ardupilot_gz/files/13327232/frames_2023-11-11_21.50.14.pdf)

**Comment by srmainwaring** [comment]
@Ryanf55 fairly certain this. was fixed in https://github.com/ArduPilot/ardupilot_gz/pull/32 where the PosePublisher plugin was removed from the models (this is the plugin publishing the parallel TF tree). Gazebo should only be publishing `odom -> base_link`, and this is output to `/gz/tf` which is relayed to `/tf` by `topic_tools` if `use_gz_tf:=true`.
